services:
    client:
        build:
            context: . # Ensure this is the root of your project
            dockerfile: ./client/Dockerfile
        container_name: client
        ports:
            - "3000:80"
    server:
        build: "./server"
        container_name: server
        ports:
            - "3001:3001"
            - "3002:3002"
        stdin_open: true
        tty: true
