services:
    client:
        image: starostwo-app-client:latest
        build:
            context: ./
            dockerfile: ./client/Dockerfile
        container_name: client
        volumes:
            - ./client:/client
            - /client/node_modules
            - ./shared:/shared # Mount shared folder
        ports:
            - "80:80"
    server:
        image: starostwo-app-server:latest
        build:
            context: ./
            dockerfile: ./server/Dockerfile
        container_name: server
        volumes:
            - ./server:/server
            - /server/node_modules
            - ./shared:/shared # Mount shared folder
        ports:
            - "3001:3001"
            - "3002:3002"
        stdin_open: true
        tty: true
