version: "3.8"
services:
    client:
        build: "./client"
        container_name: client
        ports:
            - "5173:5173"
    server:
        build: "./server"
        container_name: server
        ports:
            - "3001:3001"
            - "3002:3002"
        stdin_open: true
        tty: true
